name: Python CI

# Trigger the workflow on any push to the main branch or pull request

on:
  push:
   branches:
     -main
  pull_request:
   branches:
     -main

jobs:
  test:
    runs-on: ubantu-latest 

    steps:
    # step 1: check out code from the repository
    - name: Check out the code
      uses: actions/checkout@v2

    # step 2: Set up python environment
    - name: Set up Python
      uses: action/setup-python@v2
      with:
        python version: '3.8'

    # Install dependencies

    step 3: Install dependencies
    run:
        python -m pip install --upgrade pip
        pip install -r requirments.txt

    # Step 4: Run tests
    -name: Run tests
    run: pytest


